#==========================
# Copyleft (c) by ESWE 2021
# version 0.0.1
#==========================
name: GitHub_Actions_One
env: 
  APPLICATION_NAME   : "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask_deploy_ver_${{ github.sha }}"
  NAME_REPOSITORY    : "test_project_2"

on:
  push:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: print_hello
        run: echo "Hello World from testing"
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Execure few commands
        run: |
          echo "Hello Message_one"
          echo "Hello Message_two"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
    
      - name: List current folder
        run:  ls -la
        
      - name: Git clone repository ${{ env.NAME_REPOSITORY }}
        uses: actions/checkout@v1
        
      - name: List current folder
        run:  ls -la
    
  deploy:
    runs-on: ubuntu-latest
    needs: [testing]
    env:
      VAR_1: "This is Job level Variable1"
      VAR_2: "This is Job level Variable2"
            
    steps:
      - name: Git clone repository ${{ env.NAME_REPOSITORY }}
        uses: actions/checkout@v1
    
      - name: print_hello
        run: echo "Hello World from deploy"
        
      - name: Print env vars
        run: |
          echo "Var_1 = ${{ env.VAR_1 }}"
          echo "Var_2 = ${{ env.VAR_2 }}"
          echo "Var_3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is Local Var"
    
      - name: Printing Deployment package
        run: echo "Deploy package name is ${{ env. DEPLOY_PACKAGE_NAME }}"
    
      - name: Lets test some packages if her right thear 
        run: |
          aws --version
          zip --version
    
      - name: make_go
        run: make go
